on:
  pull_request:
  push:
    paths:
      - 'flake.lock'
      - '**/*.nix'
  workflow_call:
  workflow_dispatch:

env:
  NIX_CONFIG: |
    experimental-features = nix-command flakes

jobs:
  checks:
    runs-on: nix
    steps:
      - name: Install dependencies
        run: nix profile install nixpkgs#nodejs

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Flake checks
        uses: https://git.theless.one/actions/flake-check@v1